openapi: 3.0.3
info:
  title: SimpleSuppers API
  description: API documentation for the SimpleSuppers backend
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /person:
    post:
      summary: Create a new person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonInput'
      responses:
        '201':
          description: Person created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          description: Validation failed
        '500':
          description: Server error

components:
  schemas:
    PersonInput:
      type: object
      required:
        - firstname
        - lastname
        - email
      properties:
        firstname:
          type: string
          example: John
        lastname:
          type: string
          example: Doe
        email:
          type: string
          format: email
          example: john@example.com
        phone:
          type: string
          example: "1234567890"

    Person:
      allOf:
        - $ref: '#/components/schemas/PersonInput'
        - type: object
          properties:
            id:
              type: integer
              example: 1
            createdAt:
              type: string
              format: date-time
              example: "2024-06-12T12:00:00Z"
